In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import tensorflow as tf
import keras
import sys
import os
import random
import datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Dropout, BatchNormalization, Flatten, AveragePooling2D
from keras import Input
from keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical
from keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import LabelBinarizer

In [2]:
main_dir = os.path.dirname(sys.path[0])
main_dir

'C:\\Users\\91700\\Desktop'

In [3]:
family_link = main_dir+'/recognize_family/data/family/'
family_link

'C:\\Users\\91700\\Desktop/recognize_family/data/family/'

In [4]:
labels = set(['with_mask','without_mask'])

In [5]:
image_paths = []
image_labels = []

for label in labels:
    for image in list(os.listdir(family_link+label)):
        image_paths = image_paths + [family_link + label + '/' +image]
        image_labels = image_labels + [label]

In [6]:
np.shape(image_labels)

(7553,)

In [7]:
image_paths

['C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_10.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_100.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1000.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1001.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1002.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1003.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1004.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1005.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1006.jpg',
 'C:\\Users\\91700\\Desktop/recognize_family/data/family/with_mask/with_mask_1007.jpg',
 'C:\\Users\\91700\\Desktop/recognize_

In [8]:
image_labels

['with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with_mask',
 'with

In [9]:
data = []
for img in image_paths:
    image = cv2.imread(img)
    image = cv2.resize(image,(224,224))
    data.append(image)

In [10]:
X = np.array(data,dtype='float')

In [11]:
X

array([[[[ 35.,  63.,  57.],
         [ 28.,  55.,  46.],
         [ 32.,  55.,  45.],
         ...,
         [ 23.,  39.,  35.],
         [ 10.,  36.,  30.],
         [ 17.,  38.,  32.]],

        [[ 31.,  58.,  52.],
         [ 29.,  53.,  45.],
         [ 33.,  56.,  46.],
         ...,
         [ 46.,  60.,  56.],
         [  7.,  32.,  24.],
         [ 22.,  41.,  34.]],

        [[ 28.,  53.,  48.],
         [ 31.,  54.,  46.],
         [ 36.,  58.,  49.],
         ...,
         [ 42.,  54.,  49.],
         [ 11.,  31.,  22.],
         [ 30.,  47.,  37.]],

        ...,

        [[ 33.,  72.,  58.],
         [ 36.,  72.,  59.],
         [ 38.,  69.,  59.],
         ...,
         [ 10.,  12.,  15.],
         [  8.,  10.,  14.],
         [  8.,   9.,  15.]],

        [[ 30.,  71.,  56.],
         [ 35.,  69.,  56.],
         [ 37.,  66.,  55.],
         ...,
         [  8.,   9.,  13.],
         [ 12.,  13.,  17.],
         [ 12.,  12.,  18.]],

        [[ 27.,  69.,  52.],
       

In [12]:
y = np.array(image_labels)
y

array(['with_mask', 'with_mask', 'with_mask', ..., 'without_mask',
       'without_mask', 'without_mask'], dtype='<U12')

In [13]:
print('shape of labels :',y.shape)
print('shape of dataset :',X.shape)

shape of labels : (7553,)
shape of dataset : (7553, 224, 224, 3)


In [14]:
lb = LabelBinarizer()
y = lb.fit_transform(y.reshape(-1,1))
y = to_categorical(y)

In [15]:
np.unique(y)

array([0., 1.], dtype=float32)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [17]:
def display_image(X,y):
    fig, ax = plt.subplots(5,5,sharey=False,tight_layout=True, figsize=(12,12), facecolor='white')
    for i in range(0,5):
        for j in range(0,5):
            n = np.random.randint(0,len(y))
            ax[i,j].matshow(X[n])
            ax[i,j].set(title = y[n])
            ax[i,j].axis('off')
    plt.show()

In [18]:
INIT_LR = 1e-4
EPOCHS = 20
BS = 32

In [19]:
aug = ImageDataGenerator(rotation_range=20,zoom_range=0.15,width_shift_range=0.2,height_shift_range=0.2,shear_range=0.15,horizontal_flip=True,fill_mode='nearest')

In [20]:
base_model = MobileNetV2(weights='imagenet',include_top=False,input_tensor=Input(shape=(224,224,3)))

In [21]:
head_model = base_model.output
head_model = AveragePooling2D(pool_size=(2,2))(head_model)
head_model = Flatten(name='Flatten')(head_model)
head_model = Dense(128,activation='relu')(head_model)
head_model = Dropout(0.5)(head_model)
head_model = Dense(2,activation='softmax')(head_model)

In [22]:
model = Model(inputs=base_model.input,outputs=head_model)

In [23]:
for layer in base_model.layers:
    layer.trainable = False

In [24]:
opt = Adam(learning_rate=INIT_LR, decay=INIT_LR / EPOCHS)

In [25]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [26]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 Conv1 (Conv2D)                 (None, 112, 112, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 bn_Conv1 (BatchNormalization)  (None, 112, 112, 32  128         ['Conv1[0][0]']                  
                                )                                                             

 block_3_expand_relu (ReLU)     (None, 56, 56, 144)  0           ['block_3_expand_BN[0][0]']      
                                                                                                  
 block_3_pad (ZeroPadding2D)    (None, 57, 57, 144)  0           ['block_3_expand_relu[0][0]']    
                                                                                                  
 block_3_depthwise (DepthwiseCo  (None, 28, 28, 144)  1296       ['block_3_pad[0][0]']            
 nv2D)                                                                                            
                                                                                                  
 block_3_depthwise_BN (BatchNor  (None, 28, 28, 144)  576        ['block_3_depthwise[0][0]']      
 malization)                                                                                      
                                                                                                  
 block_3_d

 lization)                                                                                        
                                                                                                  
 block_7_expand (Conv2D)        (None, 14, 14, 384)  24576       ['block_6_project_BN[0][0]']     
                                                                                                  
 block_7_expand_BN (BatchNormal  (None, 14, 14, 384)  1536       ['block_7_expand[0][0]']         
 ization)                                                                                         
                                                                                                  
 block_7_expand_relu (ReLU)     (None, 14, 14, 384)  0           ['block_7_expand_BN[0][0]']      
                                                                                                  
 block_7_depthwise (DepthwiseCo  (None, 14, 14, 384)  3456       ['block_7_expand_relu[0][0]']    
 nv2D)    

                                                                                                  
 block_10_depthwise_relu (ReLU)  (None, 14, 14, 384)  0          ['block_10_depthwise_BN[0][0]']  
                                                                                                  
 block_10_project (Conv2D)      (None, 14, 14, 96)   36864       ['block_10_depthwise_relu[0][0]']
                                                                                                  
 block_10_project_BN (BatchNorm  (None, 14, 14, 96)  384         ['block_10_project[0][0]']       
 alization)                                                                                       
                                                                                                  
 block_11_expand (Conv2D)       (None, 14, 14, 576)  55296       ['block_10_project_BN[0][0]']    
                                                                                                  
 block_11_

 block_14_depthwise (DepthwiseC  (None, 7, 7, 960)   8640        ['block_14_expand_relu[0][0]']   
 onv2D)                                                                                           
                                                                                                  
 block_14_depthwise_BN (BatchNo  (None, 7, 7, 960)   3840        ['block_14_depthwise[0][0]']     
 rmalization)                                                                                     
                                                                                                  
 block_14_depthwise_relu (ReLU)  (None, 7, 7, 960)   0           ['block_14_depthwise_BN[0][0]']  
                                                                                                  
 block_14_project (Conv2D)      (None, 7, 7, 160)    153600      ['block_14_depthwise_relu[0][0]']
                                                                                                  
 block_14_

In [27]:
model_run = model.fit(aug.flow(X_train, y_train, batch_size=BS),
                      steps_per_epoch=len(X_train) // BS,validation_data=(X_test, y_test),validation_steps=len(X_test) // BS,epochs=EPOCHS)

Epoch 1/20
188/188 [==============================] - 223s 1s/step - loss: 0.4943 - accuracy: 0.7794 - val_loss: 0.3090 - val_accuracy: 0.8829
Epoch 2/20
188/188 [==============================] - 191s 1s/step - loss: 0.3715 - accuracy: 0.8383
Epoch 3/20
188/188 [==============================] - 156s 830ms/step - loss: 0.3422 - accuracy: 0.8591
Epoch 4/20
188/188 [==============================] - 167s 884ms/step - loss: 0.3183 - accuracy: 0.8709
Epoch 5/20
188/188 [==============================] - 167s 885ms/step - loss: 0.3054 - accuracy: 0.8742
Epoch 6/20
188/188 [==============================] - 167s 884ms/step - loss: 0.3016 - accuracy: 0.8735
Epoch 7/20
188/188 [==============================] - 169s 898ms/step - loss: 0.2846 - accuracy: 0.8850
Epoch 8/20
188/188 [==============================] - 191s 1s/step - loss: 0.2785 - accuracy: 0.8889
Epoch 9/20
188/188 [==============================] - 192s 1s/step - loss: 0.2734 - accuracy: 0.8902
Epoch 10/20
188/188 [=============

In [29]:
loss, acc = model.evaluate(X_test,y_test)

48/48 [==============================] - 38s 784ms/step - loss: 0.1966 - accuracy: 0.9252


In [31]:
print('loss : ',loss)
print('accuracy : ',acc*100)

loss :  0.19658638536930084
accuracy :  92.52150654792786


In [33]:
preds = model.predict(X_test)

In [34]:
y_preds = np.argmax(preds,axis=1)

In [35]:
y_preds

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [36]:
model.save("mask_detector.model", save_format="h5")